site_name: RideSheet
repo_url: https://github.com/full-path/ridesheet
site_url: https://full-path.github.io/ridesheet/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
nav:
  - Home: index.md
  - What is RideSheet?: what-is-ridesheet.md
  - Getting Started: getting-started.md
  - User Guide:
    - user-guide/index.md
    - Using RideSheet: user-guide/using-ridesheet.md
    - Data Fields: user-guide/data-fields.md
    - Customization: user-guide/customization.md
    - Reports: user-guide/reports.md
    - Trip Sharing and TDS: user-guide/trip-sharing-and-tds.md
    - Troubleshooting: user-guide/troubleshooting.md
    - Getting Help: user-guide/getting-help.md
  - Technical Guide: 
    - technical-guide/index.md
    - Installing RideSheet: technical-guide/installing-ridesheet.md
    - Configuration: technical-guide/configuration.md
    - Importing data: technical-guide/importing-data.md
    - Apps Script: technical-guide/apps-script.md
    - Updating the Code: technical-guide/updating-the-code.md
    - Troubleshooting: technical-guide/troubleshooting.md
  - About:
    - about/index.md 
markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  - def_list
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
docs_dir: src
edit_uri: edit/gh-pages/src/
site_dir: docs
extra_css:
  - stylesheets/ridesheet-custom.css